### ISSUE TITLE
500 error on SAML auth

### ISSUE THREAD

**Issue by goosetav** [bitium/jira-saml-plugin#3]
```
[INFO] [talledLocalContainer] java.lang.NoSuchMethodError: org.apache.xml.serializer.Encodings.isRecognizedEncoding(Ljava/lang/String;)Z
[INFO] [talledLocalContainer] 	at org.apache.xml.serializer.dom3.LSSerializerImpl.write(LSSerializerImpl.java:926)
[INFO] [talledLocalContainer] 	at org.opensaml.xml.util.XMLHelper.writeNode(XMLHelper.java:892)
[INFO] [talledLocalContainer] 	at org.opensaml.xml.util.XMLHelper.writeNode(XMLHelper.java:872)
[INFO] [talledLocalContainer] 	at org.opensaml.xml.util.XMLHelper.nodeToString(XMLHelper.java:834)
[INFO] [talledLocalContainer] 	at org.opensaml.xml.XMLConfigurator.load(XMLConfigurator.java:159)
[INFO] [talledLocalContainer] 	at org.opensaml.xml.XMLConfigurator.load(XMLConfigurator.java:143)
[INFO] [talledLocalContainer] 	at org.opensaml.DefaultBootstrap.initializeXMLTooling(DefaultBootstrap.java:203)
[INFO] [talledLocalContainer] 	at org.opensaml.DefaultBootstrap.initializeXMLTooling(DefaultBootstrap.java:186)
[INFO] [talledLocalContainer] 	at org.opensaml.DefaultBootstrap.bootstrap(DefaultBootstrap.java:92)
[INFO] [talledLocalContainer] 	at com.bitium.saml.SAMLContext.<clinit>(SAMLContext.java:43)
<snip>
```

**Comment by goosetav** [comment]
fixed

**Comment by manojgaikwad** [comment]
How to solve this error ? getting same error for plugin on JIRA 5.2.
