### ISSUE TITLE
Unable to automatically create users

### ISSUE THREAD

**Issue by robertheckel** [bitium/jira-saml-plugin#32]
JIRA v.  7.0.10

Error:
2016-02-04 16:17:15,150 http-nio-8080-exec-7 ERROR      [o.a.c.c.C.[.[localhost].[/].[servlet-module-container-servlet]] Servlet.service() for servlet [servlet-module-container-servlet] in context with path [] threw exception [Servlet execution threw an exception] with root cause
java.lang.NoSuchMethodError: com.atlassian.jira.user.util.UserUtil.createUserNoNotification(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lcom/atlassian/crowd/embedded/api/User;
	at com.bitium.jira.servlet.SsoLoginServlet.tryCreateOrUpdateUser(SsoLoginServlet.java:152)
	at com.bitium.jira.servlet.SsoLoginServlet.authenticateUserAndLogin(SsoLoginServlet.java:126)
	at com.bitium.jira.servlet.SsoLoginServlet.doPost(SsoLoginServlet.java:94)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.atlassian.plugin.servlet.DelegatingPluginServlet.service(DelegatingPluginServlet.java:42)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at com.atlassian.plugin.servlet.ServletModuleContainerServlet.service(ServletModuleContainerServlet.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	... 199 filtered
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

Deal breaker.

**Comment by robertheckel** [comment]
Will this be included in a release to the marketplace?

**Comment by rkarodia** [comment]
Yes it will
